name: CI-CD 

on:
 push:
  branches: [main]
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest
  -name: Checkout code
   uses: actions/checkout@v4
   with:
      node-version:'18'

  -name: Setup Node
   uses: actions/checkout@v4
   

  -name: Install dependencies
   run: npm install || echo "No dependecies installed"

  -name: Deploy application
   run: echo "deploying application"

 test:
  runs-on: ubuntu-latest
  needs: build 
   -name: Checkout Code
    uses: actions/checkout@v4

   -name: Test application
    run: npm test

 deploy:
  runs-on: ubuntu-latest
  needs: test
   -name: Checkout code
    uses: actions/checkout@v4

   -name: Deploying the website
    run: echo "Deploying the applications"
